# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/Comment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/Comment.proto\"\x98\x01\n\x07\x43omment\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x05\x12%\n\rcomment_state\x18\x04 \x01(\x0e\x32\x0e.Comment.State\x12\x18\n\x10publication_date\x18\x05 \x01(\x03\"\x1f\n\x05State\x12\n\n\x06NORMAL\x10\x00\x12\n\n\x06HIDDEN\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.Comment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMMENT']._serialized_start=25
  _globals['_COMMENT']._serialized_end=177
  _globals['_COMMENT_STATE']._serialized_start=146
  _globals['_COMMENT_STATE']._serialized_end=177
# @@protoc_insertion_point(module_scope)
