# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/Subreddit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/Subreddit.proto\"\x85\x01\n\tSubreddit\x12\x0c\n\x04name\x18\x01 \x01(\t\x12)\n\nvisibility\x18\x02 \x01(\x0e\x32\x15.Subreddit.Visibility\x12\x0c\n\x04tags\x18\x03 \x03(\t\"1\n\nVisibility\x12\n\n\x06PUBLIC\x10\x00\x12\x0b\n\x07PRIVATE\x10\x01\x12\n\n\x06HIDDEN\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.Subreddit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUBREDDIT']._serialized_start=27
  _globals['_SUBREDDIT']._serialized_end=160
  _globals['_SUBREDDIT_VISIBILITY']._serialized_start=111
  _globals['_SUBREDDIT_VISIBILITY']._serialized_end=160
# @@protoc_insertion_point(module_scope)
